import React from "react";
import { Activity, AlertTriangle } from "lucide-react";
import BengaluruMap from "./components/BengalurMap.jsx";

function App() {
  return (
    <div className="flex flex-col h-screen bg-gray-900 text-gray-100 overflow-hidden font-sans">
      {/* Header: Global System Status */}
      <header className="flex items-center justify-between px-6 py-4 bg-gray-800 border-b border-gray-700 shadow-md z-10">
        <div className="flex items-center space-x-3">
          <Activity className="text-blue-400" size={24} />
          <h1 className="text-xl font-bold tracking-wider">
            BTP COMMAND CENTER
          </h1>
        </div>
        <div className="flex items-center space-x-4 text-sm font-mono">
          <span className="flex items-center text-green-400">
            <span className="w-2 h-2 rounded-full bg-green-500 mr-2 animate-pulse"></span>
            SYSTEM ONLINE
          </span>
          <span className="text-gray-500">|</span>
          <span className="text-gray-400">0 ACTIVE SURGES</span>
        </div>
      </header>

      {/* Main Content Area */}
      <main className="flex flex-1 overflow-hidden">
        {/* The Live Map */}
        <section className="flex-1 relative border-r border-gray-800 bg-gray-950">
          <BengaluruMap />
        </section>

        {/* Sidebar: Real-Time Alert Feed */}
        <aside className="w-[400px] bg-gray-800 flex flex-col overflow-hidden shadow-xl z-10">
          <div className="p-4 border-b border-gray-700 bg-gray-800 shadow-sm flex justify-between items-center">
            <h2 className="text-lg font-semibold flex items-center text-red-400 tracking-wide">
              <AlertTriangle className="mr-2" size={20} />
              LIVE IMPACT FEED
            </h2>
            <span className="text-xs bg-gray-700 px-2 py-1 rounded text-gray-300 font-mono">
              AWAITING TELEMETRY
            </span>
          </div>

          {/* Alert List Container */}
          <div className="flex-1 overflow-y-auto p-4 space-y-4">
            {/* Mock Alert Card 
              (This will be dynamically generated by Zustand/WebSockets soon)
            */}
            <div className="p-4 rounded-lg bg-gray-700 border border-red-900/50 shadow-md relative overflow-hidden">
              <div className="absolute top-0 left-0 w-1 h-full bg-red-500"></div>
              <div className="flex justify-between items-start mb-2 pl-2">
                <span className="text-[10px] font-bold text-red-400 bg-red-400/10 px-2 py-1 rounded tracking-wider">
                  CRITICAL SURGE
                </span>
                <span className="text-xs text-gray-400 font-mono">
                  10:42 AM
                </span>
              </div>
              <h3 className="font-bold text-gray-100 pl-2">
                Silk Board Junction
              </h3>
              <p className="text-sm text-gray-400 mt-1 pl-2">
                Multiple vehicle breakdown detected. Severe cascading delays
                expected.
              </p>

              <div className="mt-3 text-xs text-gray-400 border-t border-gray-600 pt-3 flex justify-between pl-2">
                <span>
                  Z-Score: <span className="text-red-400 font-bold">2.4</span>
                </span>
                <span>
                  Closure Risk:{" "}
                  <span className="text-orange-400 font-bold">85%</span>
                </span>
              </div>
            </div>

            <div className="text-center text-sm text-gray-500 py-10 font-mono animate-pulse">
              Listening for WebSocket pings...
            </div>
          </div>
        </aside>
      </main>
    </div>
  );
}

export default App;
